
import java.awt.Color;
import static java.lang.System.console;
import static java.rmi.server.LogStream.log;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import static javafx.scene.input.KeyCode.R;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author fgedi
 */
public class OtomatEkrani extends javax.swing.JFrame {

    /**
     * Creates new form OtomatEkrani
     */
    public OtomatEkrani() {
        initComponents();
         lblBakiye.setText(" Bakiye: " + Float.toString(bakiye)+ "0 TL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupPara = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        lblBakiye = new java.awt.Label();
        elliRadio = new javax.swing.JRadioButton();
        birRadio = new javax.swing.JRadioButton();
        besRadio = new javax.swing.JRadioButton();
        onRadio = new javax.swing.JRadioButton();
        btnEkle = new javax.swing.JButton();
        btnEkle1 = new javax.swing.JButton();

        jDialog1.setModal(true);
        jDialog1.setSize(new java.awt.Dimension(200, 200));
        jDialog1.setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBakiye.setBackground(new java.awt.Color(0, 0, 204));
        lblBakiye.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBakiye.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblBakiye.setForeground(new java.awt.Color(255, 255, 255));

        btnGrupPara.add(elliRadio);
        elliRadio.setText("0.50 Krş");
        elliRadio.setActionCommand("50");

        btnGrupPara.add(birRadio);
        birRadio.setText("1 TL");
        birRadio.setActionCommand("1");

        btnGrupPara.add(besRadio);
        besRadio.setText("5 TL ");
        besRadio.setActionCommand("5");

        btnGrupPara.add(onRadio);
        onRadio.setText("10 TL");
        onRadio.setActionCommand("10");

        btnEkle.setText("Para Ekle");
        btnEkle.setActionCommand("btnEkle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnEkle1.setText("Para İade");
        btnEkle1.setActionCommand("btnIade");
        btnEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkle1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(elliRadio)
                        .addGap(28, 28, 28)
                        .addComponent(birRadio)
                        .addGap(37, 37, 37)
                        .addComponent(besRadio)
                        .addGap(18, 18, 18)
                        .addComponent(onRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elliRadio)
                            .addComponent(birRadio)
                            .addComponent(besRadio)
                            .addComponent(onRadio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        lblBakiye.getAccessibleContext().setAccessibleName("lblBakiye");
        lblBakiye.getAccessibleContext().setAccessibleDescription("");
        onRadio.getAccessibleContext().setAccessibleName("onRadio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 359, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 float bakiye=0;
 
    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
      
       String secilenPara = btnGrupPara.getSelection().getActionCommand ();
       
        
        switch(secilenPara)
       {
           case "50":
               bakiye = (float) (bakiye + 0.50);
           lblBakiye.setText(" Bakiye: " + Float.toString(bakiye)+ " TL");
               break;
               
           case "1":
               bakiye = (float) (bakiye + 1);
           lblBakiye.setText(" Bakiye: " + Float.toString(bakiye)+ " TL");
               break;
               
           case "5":
               bakiye = (float) (bakiye + 5);
           lblBakiye.setText(" Bakiye: " + Float.toString(bakiye)+ " TL");
               break;
               
           case "10":
               bakiye = (float) (bakiye + 10);
           lblBakiye.setText(" Bakiye: " + Float.toString(bakiye)+ " TL");
               break;
           default:
                JOptionPane.showMessageDialog(this, "Paranız İade Ediliyor","Lütfen Bekleyiniz",JOptionPane.INFORMATION_MESSAGE);
            
       }
        
//      
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkle1ActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(this, "Paranız İade Ediliyor","Lütfen Bekleyiniz",JOptionPane.INFORMATION_MESSAGE);
        
        bakiye = 0;
        lblBakiye.setText(" Bakiye: " + bakiye + " TL");

    }//GEN-LAST:event_btnEkle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtomatEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtomatEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtomatEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtomatEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtomatEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton besRadio;
    private javax.swing.JRadioButton birRadio;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnEkle1;
    private javax.swing.ButtonGroup btnGrupPara;
    private javax.swing.JRadioButton elliRadio;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblBakiye;
    private javax.swing.JRadioButton onRadio;
    // End of variables declaration//GEN-END:variables
}
